### ISSUE TITLE
Where to store user data (history, favorites etc)

### ISSUE THREAD

**Issue by joehoyle** [fernyb/Sequel-J#16]
I noticed the Save History had been implemented, seemingly by downloading a file on the user's computer? 

I wondered how best to handle the user's favorites, saves queries etc? Perhaps it would be best to store in localStorage (at least for now)?

**Comment by fernyb** [comment]
Yeah saving to localStorage is probably the best way of doing that now.

Thats why I'm using CPUserDefaults it uses the localStorage if the browser supports it otherwise uses a cookie. (http://cappuccino.org/learn/documentation/interface_c_p_user_defaults.html)

To download the local data it creates an iframe and sends the data to the server and the server then sends an attachment and the browser will then download that attachment.

I took the advice from: 
http://groups.google.com/group/objectivej/browse_thread/thread/e8242a8d91216741/5276536023f41678?lnk=gst&q=DownloadIFrame&pli=1

**Comment by joehoyle** [comment]
Ahh I see. I guess for full DB exports we would probably just want the server to pass the export. Rather than DB -> Capp -> Backend -> Download (thinking for very large DBs).

**Comment by fernyb** [comment]
Yeah for large downloads we just want the server to pass the export.
