### ISSUE TITLE
hitting tab key should focus on next textfield

### ISSUE THREAD

**Issue by fernyb** [fernyb/Sequel-J#5]
In the login view hitting the tab key should focus on the next textfield.
I'm not sure what happen but when I initially wrote it it was working.

When I updated the frameworks its possible that is when it started to fail.

**Comment by joehoyle** [comment]
After a lengthly amount of debugging - I tracked it now to the `LPMultilineTextField` in `SJTableInfoTabController.j`. I imagine there is a bug with `LPMultilineTextField` swallowing the nextResponder or something. If you change line 329 to 

```
  var textbox = [[CPTextField alloc] initWithFrame:CGRectMake(textboxOriginX, 2, textboxSizeWidth - 5, labelVieSizeHeight - 4)];
```

Then the tabbing is fixed. I also tried running it against Cappuccino 0.9 (rather than master) but that didn't fix it.
